/:
  controller: HomeController
  action: index

### Auth routes ###
/register:
  controller: AuthController
  action: register

/login:
  controller: AuthController
  action: login

/logout:
  controller: AuthController
  action: logout

/forgot-password:
  controller: AuthController
  action: forgotPassword

/reset-password:
  controller: AuthController
  action: resetPassword

/activate-account:
  controller: AuthController
  action: activateAccount

### Page routes ###
/page:
  controller: PageController
  action: show

### Admin pages routes ###
/admin/pages:
  controller: PageController
  action: index

/admin/page:
  controller: PageController
  action: admin_show

/admin/page/create:
  controller: PageController
  action: create

/admin/page/edit:
  controller: PageController
  action: edit

/admin/page/delete:
  controller: PageController
  action: delete

### Admin posts routes ###
/admin/posts:
  controller: PostController
  action: index

/admin/post:
  controller: PostController
  action: admin_show

/admin/post/create:
  controller: PostController
  action: create

/admin/post/edit:
  controller: PostController
  action: edit

/admin/post/delete:
  controller: PostController
  action: delete

### Admin features ###
/export-solution:
  controller: FeatureController
  action: exportSolution

### Error pages ###
/404:
  controller: Error
  action: error404
